name = "NUMAHelper"
uuid = "c3ff8000-7e65-4602-bf2f-c74abbbfe255"
authors = ["Felipe Alves <felipe.alves.br@nps.edu>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
